name: JetPack
api: [3.0.0]
main: bbo51dog\jetpack\JetPackPlugin
version: 1.1.0-dev
description: Jet pack plugin
author: bbo51dog
permissions:
  jetpack.*:
    default: false
    children:
      jetpack.command:
        default: true